### ISSUE TITLE
Tried to Run Code in Java, but Ran in Python

### ISSUE THREAD

**Issue by loop0919** [judge0/judge0-python#10]
**Describe the bug**

**To Reproduce**

- Execute this Python code
```py
import judge0

JUDGE_API_URL = "http://my.own.server:2358"
CLIENT = judge0.Client(endpoint=JUDGE_API_URL, auth_headers={"Content-Type": "application/json"})


if __name__ == "__main__":
    code = '''\
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}
'''
    submission = judge0.Submission(
        source_code=code,
        language=judge0.LanguageAlias.JAVA,
    )
    print(submission.language)
    result = judge0.run(client=CLIENT, submissions=submission)
    print(result.language)
    print(result.status)
    print(result.stderr)
```

- Output it

```
LanguageAlias.JAVA
LanguageAlias.PYTHON
Runtime Error Nzec
  File "script.py", line 1
    public class Main {
           ^
SyntaxError: invalid syntax
```

**Expected behavior**
It would be executed by Java.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2023
 - Browser chrome
 - Version Python3.10.12, Judge0 v1.13.1

**Additional context**
Using server crerated by [https://github.com/judge0/judge0](https://github.com/judge0/judge0) v1.13.1

**Comment by fkdosilovic** [comment]
Thanks for submitting the issue. The issue is fixed in the new release which is available on PyPI. Note that there were some notable changes in the lib since the last release - mainly we now rely on pydantic.
